### ISSUE TITLE
Page does not load.

### ISSUE THREAD

**Issue by liyakurkov** [codefellows/PGP-Web-App#9]
The following message is displayed when I attempt to access the application: "An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

**Comment by dcorns** [comment]
Sorry, you probably were not using chrome. The app is only tested for chrome right now.

Sent via the ASUS PadFone X, an AT&T 4G LTE smartphone

-------- Original Message --------

**Comment by nchornesky** [comment]
Hi. I am using Chrome and cannot get the page to load . . .

**Comment by Klamklam90** [comment]
I am also using chrome and I got the same error

**Comment by dcorns** [comment]
Try accessing from an incognito window CRTL+SHIFT+N or CMD+SHIFT+N and see if it works. Maybe something funny has been cashed into the browser.Date: Sat, 28 Feb 2015 15:16:28 -0800

**Comment by jesseprice** [comment]
Getting the same error message when trying to open using Safari, and Chrome, and the suggested method above in Chrome.  I was able to access once a few days ago, but now not working again.

**Comment by pvl1720** [comment]
Hi there! 
Same error on two different computers using chrome, tried incognito also.
at first, I was able to sign in, answer the Qs and check the box at the bottom, but the page wouldn't accept my responses. Now there's just the App Error msg

**Comment by dcorns** [comment]
You saved your survey as complete, so you should be getting a message stating that your personal growth plan will appear when it has been completed. Once you save your survey as complete, you no longer have access to it.Date: Mon, 2 Mar 2015 18:49:06 -0800

**Comment by dcorns** [comment]
I have not been able to duplicate any of these problems. If you have further issues, submit a new issue including the time that it occurred and your username.
